modbus_controller:
  - id: tongdy
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms

sensor:
  - platform: modbus_controller
    modbus_controller_id: tongdy
    name: "TG9 Temperatuur"
    register_type: custom
    custom_command:
      function_code: 0x04
      start_address: 1004
      register_count: 2
    response_callback: modbus_controller_fp32
    value_type: FP32
    unit_of_measurement: "°C"
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: tongdy
    name: "TG9 Relatieve Vochtigheid"
    register_type: custom
    custom_command:
      function_code: 0x04
      start_address: 1006
      register_count: 2
    response_callback: modbus_controller_fp32
    value_type: FP32
    unit_of_measurement: "%"
    accuracy_decimals: 2

  # ... herhaal voor alle sensors, pas adres en register_count aan!
